-- MySQL Script generated by MySQL Workbench
-- 05/27/17 17:38:56
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ranm
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ranm
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ranm` DEFAULT CHARACTER SET utf8 ;
USE `ranm` ;

-- -----------------------------------------------------
-- Table `ranm`.`Velocidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ranm`.`Velocidad` ;

CREATE TABLE IF NOT EXISTS `ranm`.`Velocidad` (
  `ID_Velocidad` INT NOT NULL AUTO_INCREMENT,
  `NS_V` FLOAT NULL,
  `EO_V` FLOAT NULL,
  `Z_V` FLOAT NULL,
  PRIMARY KEY (`ID_Velocidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ranm`.`Desplazamiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ranm`.`Desplazamiento` ;

CREATE TABLE IF NOT EXISTS `ranm`.`Desplazamiento` (
  `ID_Desplazamiento` INT NOT NULL AUTO_INCREMENT,
  `NS_D` FLOAT NULL,
  `EO_D` FLOAT NULL,
  `Z_D` FLOAT NULL,
  PRIMARY KEY (`ID_Desplazamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ranm`.`Aceleracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ranm`.`Aceleracion` ;

CREATE TABLE IF NOT EXISTS `ranm`.`Aceleracion` (
  `ID_Aceleracion` INT NOT NULL AUTO_INCREMENT,
  `NS_A` FLOAT NULL,
  `EO_A` FLOAT NULL,
  `Z_A` FLOAT NULL,
  PRIMARY KEY (`ID_Aceleracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ranm`.`Espectro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ranm`.`Espectro` ;

CREATE TABLE IF NOT EXISTS `ranm`.`Espectro` (
  `ID_Espectros` INT NOT NULL AUTO_INCREMENT,
  `NS_E` FLOAT NULL,
  `EO_E` FLOAT NULL,
  `Z_E` FLOAT NULL,
  PRIMARY KEY (`ID_Espectros`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ranm`.`Intensidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ranm`.`Intensidad` ;

CREATE TABLE IF NOT EXISTS `ranm`.`Intensidad` (
  `ID_Intensidad` INT NOT NULL AUTO_INCREMENT,
  `Velocidad` INT NULL,
  `Aceleracion` INT NULL,
  `Desplazamiento` INT NULL,
  `Espectros` INT NULL,
  PRIMARY KEY (`ID_Intensidad`),
  INDEX `Velocidad_idx` (`Velocidad` ASC),
  INDEX `Desplazamiento_idx` (`Desplazamiento` ASC),
  INDEX `Aceleracion_idx` (`Aceleracion` ASC),
  INDEX `Espectros_idx` (`Espectros` ASC),
  CONSTRAINT `Velocidad`
    FOREIGN KEY (`Velocidad`)
    REFERENCES `ranm`.`Velocidad` (`ID_Velocidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Desplazamiento`
    FOREIGN KEY (`Desplazamiento`)
    REFERENCES `ranm`.`Desplazamiento` (`ID_Desplazamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Aceleracion`
    FOREIGN KEY (`Aceleracion`)
    REFERENCES `ranm`.`Aceleracion` (`ID_Aceleracion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Espectros`
    FOREIGN KEY (`Espectros`)
    REFERENCES `ranm`.`Espectro` (`ID_Espectros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ranm`.`Nivel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ranm`.`Nivel` ;

CREATE TABLE IF NOT EXISTS `ranm`.`Nivel` (
  `ID_Espectro` INT NOT NULL,
  `Estacion` VARCHAR(150) NOT NULL COMMENT 'Nombre de la estacion',
  `Intensidad` INT NOT NULL COMMENT 'Aceleracion norte - sur',
  `Distancia` FLOAT NOT NULL COMMENT 'Distancia del epicentro a la estacion',
  `Codigo_Estacion` INT NULL,
  PRIMARY KEY (`ID_Espectro`),
  INDEX `Intensidad_idx` (`Intensidad` ASC),
  CONSTRAINT `Intensidad`
    FOREIGN KEY (`Intensidad`)
    REFERENCES `ranm`.`Intensidad` (`ID_Intensidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ranm`.`Estaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ranm`.`Estaciones` ;

CREATE TABLE IF NOT EXISTS `ranm`.`Estaciones` (
  `ID_Estaciones` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Estacion` VARCHAR(30) NOT NULL COMMENT 'Nombre de la estacion',
  `Sitio` VARCHAR(150) NOT NULL COMMENT 'Region, ciudad o lugar donde esta colocada',
  `Latitud_Estacion` FLOAT NOT NULL COMMENT 'Coordenadas norte - sur',
  `Longitud_Estacion` FLOAT NOT NULL COMMENT 'Coordenada este - oeste',
  `Elevacion` FLOAT NOT NULL COMMENT 'Elevacion',
  `Aceleracion_Estacion` VARCHAR(150) NOT NULL COMMENT 'Tipo de Acelerometro que tiene',
  `GPS` VARCHAR(150) NOT NULL COMMENT 'Tipo de GPS que tiene',
  `Velocidad_Estacion` VARCHAR(150) NULL COMMENT 'Tipo de Velocilometro que contiene la estacion',
  `Digitalizador_Estacion` VARCHAR(150) NULL COMMENT 'Marca de Digitalizacio que tiene la estacion',
  `Niveles` INT NULL,
  PRIMARY KEY (`ID_Estaciones`),
  INDEX `Niveles_idx` (`Niveles` ASC),
  CONSTRAINT `Niveles`
    FOREIGN KEY (`Niveles`)
    REFERENCES `ranm`.`Nivel` (`ID_Espectro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ranm`.`Sismo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ranm`.`Sismo` ;

CREATE TABLE IF NOT EXISTS `ranm`.`Sismo` (
  `ID_Sismo` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL COMMENT 'Dia cuando ocurrio el sismo',
  `Hora` TIME(0) NOT NULL COMMENT 'Hora cuando ocurrio el evento UTC',
  `Magnitud` FLOAT NOT NULL COMMENT 'Magnitud del evento',
  `Latitud_Sismo` FLOAT NOT NULL COMMENT 'Coordenadas norte - sur del evento',
  `Longitud_Sismo` FLOAT NOT NULL COMMENT 'Coordenadas este - oeste del evento',
  `Estaciones` INT NOT NULL,
  `Nombre_Sismo` VARCHAR(150) NULL,
  `Distancia_Epicentral` FLOAT NULL,
  PRIMARY KEY (`ID_Sismo`),
  INDEX `estaciones_idx` (`Estaciones` ASC),
  CONSTRAINT `estaciones`
    FOREIGN KEY (`Estaciones`)
    REFERENCES `ranm`.`Estaciones` (`ID_Estaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ranm`.`Texto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ranm`.`Texto` ;

CREATE TABLE IF NOT EXISTS `ranm`.`Texto` (
  `ID_Texto` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Tema` VARCHAR(100) NULL COMMENT 'Nombre del titulo principal',
  `Descripcion` VARCHAR(4000) NOT NULL COMMENT 'Desarrolla el texto del tema',
  `Lugar` VARCHAR(100) NOT NULL COMMENT 'Donde se colocara el texto dentro de la pagina',
  PRIMARY KEY (`ID_Texto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ranm`.`Contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ranm`.`Contacto` ;

CREATE TABLE IF NOT EXISTS `ranm`.`Contacto` (
  `ID_Contacto` INT NOT NULL AUTO_INCREMENT,
  `Nombre_Persona` VARCHAR(100) NOT NULL COMMENT 'Nombre dela persona quien se comunuca',
  `Correo` VARCHAR(150) NOT NULL COMMENT 'Correo donde se envia la informacion',
  `Mensaje` VARCHAR(200) NOT NULL COMMENT 'Mensaje que se enva al administrador',
  PRIMARY KEY (`ID_Contacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ranm`.`Admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ranm`.`Admin` ;

CREATE TABLE IF NOT EXISTS `ranm`.`Admin` (
  `ID_Admin` INT NOT NULL AUTO_INCREMENT,
  `Contacto` INT NOT NULL,
  `Letra` INT NOT NULL,
  `Sismo` INT NOT NULL,
  PRIMARY KEY (`ID_Admin`),
  INDEX `sismo_idx` (`Sismo` ASC),
  INDEX `contacto_idx` (`Contacto` ASC),
  INDEX `letras_idx` (`Letra` ASC),
  CONSTRAINT `sismo`
    FOREIGN KEY (`Sismo`)
    REFERENCES `ranm`.`Sismo` (`ID_Sismo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `contacto`
    FOREIGN KEY (`Contacto`)
    REFERENCES `ranm`.`Contacto` (`ID_Contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `letras`
    FOREIGN KEY (`Letra`)
    REFERENCES `ranm`.`Texto` (`ID_Texto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
